### ISSUE TITLE
Can't get Code Preview to work

### ISSUE THREAD

**Issue by neon-age** [needle-tools/demystify#3]
It shows up only on messages that weren't demystified (right after installation), and only when log-view is focused.

![GIF 10 03 2021 20-53-22](https://user-images.githubusercontent.com/29812914/110639784-affb3500-81e2-11eb-98cf-4f10ac709c1c.gif)

Code Preview Key is not assigned.

**Comment by marwie** [comment]
Hello, I fixed some issues with it showing up right after installation/after some layout changes. Which version are you currently using? Could you try either ``1.1.0-pre.7`` or ``1.2.0-exp.2`` ?

**Comment by neon-age** [comment]
I've tried in both versions and it was the same issue

**Comment by marwie** [comment]
Ok I was not decoding the URI when making the path relative. Will push a fix in a minute

**Comment by marwie** [comment]
It's pending on OpenUPM. Let me know if it fixed it for you
https://openupm.com/packages/com.needle.demystify/?subPage=pipelines

(pushed for ``1.2.0-exp.3`` and ``1.1.0-pre.8``)

**Comment by neon-age** [comment]
Damn you're fast! Yeah, this one seems to be fixed.

**Comment by marwie** [comment]
Awesome!
