### ISSUE TITLE
Repository Projects have missing 'Editor Patching' package

### ISSUE THREAD

**Issue by neon-age** [needle-tools/demystify#5]
![image](https://user-images.githubusercontent.com/29812914/110734790-1e7bd980-825b-11eb-8d52-f0cd06853320.png)

Can be resolved by installing 'Editor Patching' from OpenUPM registry

**Comment by marwie** [comment]
Ah you forked this repo? Yes, internally this repo is a submodule of EditorPatching and the package is references locally.
